trace: false

server:
  port: 5000

spring:
  profiles:
    include:
      - domain
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:api;DB_CLOSE_ON_EXIT=FALSE;DB_CLOSE_DELAY=-1;
    username: user
    password: pass
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true

  redis:
    host: localhost
    port: 6379
logging:
  level:
    org.hibernate:
      SQL: debug
      type: debug
    com.zaxxer.hikari.HikariDataSource: error

cloud:
  aws:
    # IAM 사용자 액세스, 비밀 키
    credentials:
      accessKey: AKIAWFB2UL6ZRAXEPR5J
      secretKey: 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
    s3:
      # s3 버킷 이름
      bucket: howhair
    region:
      # 지역
      static: ap-northeast-2
    stack:
      auto: false
    url : https://howhair.s3.ap-northeast-2.amazonaws.com